# Curso de Python - Ricardo Malheiro (ricardo.malheiro@ipleiria.pt)

## Numpy

O Numpy é uma das bibliotecas fundamentais do python, utilizada para trabalhar com matrizes e arrays n-dimensionais (ndarrays).
Esta biblioteca está incluída no pacote de computação científica ScyPy.
A biblioteca está otimizada para lidar com computação vetorizada possuindo funcionalidades para manipulação de vetores/matrizes muito mais eficientes do que as utilizadas em ciclos de repetição.

In [2]:
#O primeiro passo consiste em importar a biblioteca numpy
import numpy as np

In [61]:
#Cria uma matriz unidimensional
mt = np.array([2,24,33,12,40, 66])
print(mt)
print(type(mt))

[ 2 24 33 12 40 66]
<class 'numpy.ndarray'>


In [8]:
#Criar o array com um tipo específico
#Cria o array com inteiros
mtint = np.array([5, 6, 7], dtype = np.int32)
print(mtint)
print(type(mtint))

#Cria o array como float de 64 bits
mtfloat = np.array([5, 6, 7], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))

[5 6 7]
<class 'numpy.ndarray'>
[5. 6. 7.]
<class 'numpy.ndarray'>


In [9]:
#Alterar o tipo de dados do array
mt = np.array([3.9999, 1.226, 25.13, -9.42, 7])
print(mt)

#De float para int (os valores são truncados)
mtint = mt.astype(np.int32)
print(mtint)

[ 3.9999  1.226  25.13   -9.42    7.    ]
[ 3  1 25 -9  7]


In [10]:
#Alterar o tipo de dados do array
mt = np.array([2, 3, 4, 6, 7])
print(mt)

#De para int para float
mtfloat = mt.astype(float)
print(mtfloat)

[2 3 4 6 7]
[2. 3. 4. 6. 7.]


In [14]:
#Cria uma matriz bidimensional
mt = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mt)
print(type(mt))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [15]:
#Criar array em que os elementos não são inicializados (3 linhas e 3 colunas)
vazio = np.empty([3,3], dtype = int)
print(vazio)

print()
#Cria uma matriz 2x4 com valores zero
zero = np.zeros([2,4])
print(zero)

print()
#Cria uma matriz 3x2 com valores um
um = np.ones([3,2])
print(um)

print()
# cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(3)
print(diagonal)

[[-575935568        458          1]
 [         0 -509110592        458]
 [-529225152        458          0]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
#Matriz com valores aleatórios entre 0 e 1
aleat = np.random.random((4))
print(aleat)
print()

#Matriz com valores aleatórios entre 0 e 100
aleat = 100*np.random.random((3, 4))
print(aleat)
print()

#Matriz com valores aleatórios. Distribuição normal contendo negativos
aleat= np.random.randn((4))
print(aleat)
print()

[0.69546869 0.52144135 0.80444204 0.25969532]

[[80.89565226 83.2103428  87.81164201 88.83190188]
 [12.3112668  77.71912876 82.40509097  4.01267703]
 [51.88437587 77.46467029 15.33866874 59.36573076]]

[ 1.60759061  0.4411118   0.41782061 -0.3097681 ]



In [56]:
#Outra forma de gerar aleatórios utilizando a semente
na = np.random.default_rng(1)
aleat = na.random(3)
print (aleat)

print()

#Gerar uma matriz 3x3 de numeros inteiros entre 0 e 20
aleat = na.integers(20, size=(3, 3))
print(aleat)

[0.51182162 0.9504637  0.14415961]

[[16 18  4]
 [ 6 17  8]
 [ 5 16  5]]


In [64]:
#Eliminar repetições
x = np.array([2, 4, 5, 7, 98, 23, 23, 23, 7, 98, 2])
print(x)

x = np.unique(x)
print(x)

[ 2  4  5  7 98 23 23 23  7 98  2]
[ 2  4  5  7 23 98]


In [70]:
#Aceder a elementos
#Cria a matriz mt
mt = np.array([[7,12,241],[17,20,16],[83,44,2]])
# Mostra a matriz mt
print(mt)

print()

# Mostra um elemento na posição (1, 1) da matriz
print(mt[1][1])

print()

# Mostra o tamanho das dimensões da matriz mt
print(mt.shape)

[[  7  12 241]
 [ 17  20  16]
 [ 83  44   2]]

20

(3, 3)


In [72]:
#Funções Matemáticas

#Mostra o maior valor da matriz 
print(mt.max())

#Mostra o menor valor da matriz
print(mt.min())

#Mostra a soma dos valores da matriz
print((mt.sum()))

#Mostra o valor da média dos valores da matriz
print(mt.mean())

#Mostra o valor do desvio padrão (standard deviation) dos valores da matiz
print(mt.std())

241
2
442
49.111111111111114
71.75644677881554


In [75]:
#Funções aplicadas a todos os elementos da matriz
mt = np.array([1, 4, 9, 16, 25, 36])

#Mostra o valor da raiz quadrada de todos elementos
print(np.sqrt(mt))

print()

# Mostra o valor do exponencial de todos elementos
print(np.exp(mt))

[1. 2. 3. 4. 5. 6.]

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [77]:
#Extração de elementos
mt = np.array([1, 2, 3, 4, 5, 6])

#Mostra o elemento da posição 3
print(mt[2])

#Mostra o array criado a partir da posição 0, dois elementos
print(mt[0:2])

#Mostra o array criado a partir da 2a posição
# até todo o restante do array
print(mt[1:])

#Mostra o array criado a partir da antepenúltima
#posição até o final
print(mt[-3:])

3
[1 2]
[2 3 4 5 6]
[4 5 6]


In [80]:
#Extração de linhas e colunas
mt = np.array([[4, 5], [6, 1], [7, 4]])
print(mt)

print()

#Primeira linha, todas as colunas
mt_linha_1 = mt[0, :]
print(mt_linha_1)

print()

#Segunda linha
mt_linha_2 = mt[1, :]
print(mt_linha_2)

print()

#Terceira linha
mt_linha_3 = mt[2, :]
print(mt_linha_3)

print()

#Todas as linhas, primeira coluna
mt_coluna_1 = mt[:, 0]
print(mt_coluna_1)

print()

#Todas as linhas, segunda coluna
mt_coluna_2 = mt[:, 1]
print(mt_coluna_2)

[[4 5]
 [6 1]
 [7 4]]

[4 5]

[6 1]

[7 4]

[4 6 7]

[5 1 4]


In [82]:
#Adição e multiplicação de matrizes
mt1 = np.array([[1, 2], [3, 4]])
mt2 = np.array([[1, 1], [1, 1]])
soma_mt = mt1 + mt2
print(soma_mt)

print()

prod_mt = mt1 * mt2
print(prod_mt)

print()

mt1 = np.array([[1, 2], [3, 4], [5, 6]])
mt2 = np.array([[2, 1]])
print(mt1 + mt2)

[[2 3]
 [4 5]]

[[1 2]
 [3 4]]

[[3 3]
 [5 5]
 [7 7]]


In [87]:
#Função 'arrange' dispõe um conjunto de 15 elementos (de 0 a 14) numa matriz de 3 linhas e 5 colunas
f = np.arange(15).reshape((3, 5))
print(f)

print()

#Calcula a matriz transposta
s = f.T
print(s)

print()

#Outra forma de calcular a matriz transposta
s = f.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [88]:
#Expressões lógicas
#usando where

#Criar uma matriz com valores aleatórios positivos e negativos
mt = np.random.randn(3, 3)
print(mt)

print()

#Criar uma matriz com valores booleanos baseado na matriz mt
mt2 = (mt > 0)
print(mt2)

print()

#Criar uma matriz com valores -1 e 1 baseado nos valores da matriz mt2
mt3 = np.where(mt2 > 0, 1, -1)
print(mt3)

[[-1.08518369  0.65941639 -0.25854751]
 [ 1.54719928  0.8979245  -0.12947312]
 [-0.39098036  0.67045523  0.81344832]]

[[False  True False]
 [ True  True False]
 [False  True  True]]

[[-1  1 -1]
 [ 1  1 -1]
 [-1  1  1]]
